SELECT LTRIM(RTRIM(SD_CUST_NAME)) as "Customer Name",
           SD_CUST_CODE as "Customer Code",
           NVL(R.INVH_SM_CODE, S.CSRH_SM_CODE) as "SM Code",
           NVL(R.SM_NAME, S.SM_NAME) as "SM Name",
           TO_CHAR(SD_DT, 'DD/MM/YYYY') as "Sale Date",
           SD_TXN_CODE||'-'||TO_CHAR(SD_NO) as "Transaction No",
           SD_SALE_LOCN_CODE as "Location Code",
           SD_ITEM_CODE as "Item Code",
           ITEM_NAME as "Item Name",
           SD_GRADE_CODE as "Grade Code",
           C.AD_NAME as "Class Name",
           D.AD_NAME as "Brand Name",
           E.AD_NAME as "Manufacturer Name",
           F.AD_NAME as "TBU",
           G.AD_NAME as "Category Name",
           H.AD_NAME as "Rim Size",
           I.AD_NAME as "Radial Bias",
           J.AD_NAME as "Product Line",
           K.AD_NAME as "Manufacturer Group",
           L.AD_NAME as "Sales Name",
           M.AD_NAME as "COS Name",
           N.AD_NAME as "Tyre Size",
           O.AD_NAME as "Old Category",
           P.AD_NAME as "GYR VCODE",
           Q.AD_NAME as "GYR IG",
           DECODE(SD_TXN_TYPE, 'INV', NVL(SD_QTY_BU,0)/IU_MAX_LOOSE_1, -1*(NVL(SD_QTY_BU,0)/IU_MAX_LOOSE_1)) as "Quantity",
           DECODE(SD_TXN_TYPE, 'INV', NVL(SD_ITEM_VAL,0), -1*NVL(SD_ITEM_VAL,0)) as "Item Value",
           DECODE(SD_TXN_TYPE, 'INV', NVL(SD_DISC_VAL,0), -1*NVL(SD_DISC_VAL,0)) as "Discount Value",
           DECODE(SD_TXN_TYPE, 'INV', NVL(SD_VAT_VAL,0), -1*NVL(SD_VAT_VAL,0)) as "VAT Value",
           DECODE(NVL(R.INVH_STATUS, NVL(S.CSRH_STATUS,0)), 0, NULL, DECODE(SD_TXN_TYPE, 'INV', (NVL(SD_QTY_BU,0)/IU_MAX_LOOSE_1)*NVL(SD_WAC,0), -1*((NVL(SD_QTY_BU,0)/IU_MAX_LOOSE_1)*NVL(SD_WAC,0)))) as "Cost",
           DECODE(SD_TXN_TYPE, 'INV', (NVL(SD_ITEM_VAL,0)-NVL(SD_DISC_VAL,0)+NVL(SD_VAT_VAL,0)), -1*(NVL(SD_ITEM_VAL,0)-NVL(SD_DISC_VAL,0)+NVL(SD_VAT_VAL,0))) as "Sales Value",
           DECODE(SD_TXN_TYPE, 'INV', (NVL(SD_ITEM_VAL,0)-NVL(SD_DISC_VAL,0)), -1*(NVL(SD_ITEM_VAL,0)-NVL(SD_DISC_VAL,0))) as "Excl VAT",
           DECODE(NVL(R.INVH_STATUS, NVL(S.CSRH_STATUS,0)), 0, NULL, DECODE(SD_TXN_TYPE, 'INV', (NVL(SD_ITEM_VAL,0)-NVL(SD_DISC_VAL,0))-((NVL(SD_QTY_BU,0)/IU_MAX_LOOSE_1)*NVL(SD_WAC,0)),
           -1*((NVL(SD_ITEM_VAL,0)-NVL(SD_DISC_VAL,0))-((NVL(SD_QTY_BU,0)/IU_MAX_LOOSE_1)*NVL(SD_WAC,0))))) as "Contribution",
           DECODE(NVL(R.INVH_STATUS, NVL(S.CSRH_STATUS,0)), 0, NULL, DECODE(SD_ITEM_VAL,0,0,
           DECODE((NVL(SD_ITEM_VAL,0)-NVL(SD_DISC_VAL,0)),0,0,
           DECODE(NVL(SD_WAC,0),0, 0,
            ROUND(((NVL(SD_ITEM_VAL,0)-NVL(SD_DISC_VAL,0))-((NVL(SD_QTY_BU,0)/IU_MAX_LOOSE_1)*NVL(SD_WAC,0)))/(NVL(SD_ITEM_VAL,0)-NVL(SD_DISC_VAL,0))*100,2))))) as "Margin %",
           TO_NUMBER(TO_CHAR(SD_DT,'YYYYMM')) as "YYYYMM",
           T.AD_NAME as "Customer Type"
    FROM  OS_SALES_DETAIL, OM_ITEM, OM_ITEM_UOM, OM_CUSTOMER,
    (SELECT VSSV_VS_CODE, VSSV_CODE, VSSV_NAME FROM IM_VS_STATIC_VALUE ) A,
    (SELECT AD_ANLY_TYPE, AD_ANLY_NO, AD_CODE, AD_PARENT_CODE, AD_NAME FROM OM_ANALYSIS_DETAIL) C,
    (SELECT AD_ANLY_TYPE, AD_ANLY_NO, AD_CODE, AD_PARENT_CODE, AD_NAME FROM OM_ANALYSIS_DETAIL) D,
    (SELECT AD_ANLY_TYPE, AD_ANLY_NO, AD_CODE, AD_PARENT_CODE, AD_NAME FROM OM_ANALYSIS_DETAIL) E,
    (SELECT AD_ANLY_TYPE, AD_ANLY_NO, AD_CODE, AD_PARENT_CODE, AD_NAME FROM OM_ANALYSIS_DETAIL) F,
    (SELECT AD_ANLY_TYPE, AD_ANLY_NO, AD_CODE, AD_PARENT_CODE, AD_NAME FROM OM_ANALYSIS_DETAIL) G,
    (SELECT AD_ANLY_TYPE, AD_ANLY_NO, AD_CODE, AD_PARENT_CODE, AD_NAME FROM OM_ANALYSIS_DETAIL) H,
    (SELECT AD_ANLY_TYPE, AD_ANLY_NO, AD_CODE, AD_PARENT_CODE, AD_NAME FROM OM_ANALYSIS_DETAIL) I,
    (SELECT AD_ANLY_TYPE, AD_ANLY_NO, AD_CODE, AD_PARENT_CODE, AD_NAME FROM OM_ANALYSIS_DETAIL) J,
    (SELECT AD_ANLY_TYPE, AD_ANLY_NO, AD_CODE, AD_PARENT_CODE, AD_NAME FROM OM_ANALYSIS_DETAIL) K,
    (SELECT AD_ANLY_TYPE, AD_ANLY_NO, AD_CODE, AD_PARENT_CODE, AD_NAME FROM OM_ANALYSIS_DETAIL) L,
    (SELECT AD_ANLY_TYPE, AD_ANLY_NO, AD_CODE, AD_PARENT_CODE, AD_NAME FROM OM_ANALYSIS_DETAIL) M,
    (SELECT AD_ANLY_TYPE, AD_ANLY_NO, AD_CODE, AD_PARENT_CODE, AD_NAME FROM OM_ANALYSIS_DETAIL) N,
    (SELECT AD_ANLY_TYPE, AD_ANLY_NO, AD_CODE, AD_PARENT_CODE, AD_NAME FROM OM_ANALYSIS_DETAIL) O,
    (SELECT AD_ANLY_TYPE, AD_ANLY_NO, AD_CODE, AD_PARENT_CODE, AD_NAME FROM OM_ANALYSIS_DETAIL) P,
    (SELECT AD_ANLY_TYPE, AD_ANLY_NO, AD_CODE, AD_PARENT_CODE, AD_NAME FROM OM_ANALYSIS_DETAIL) Q,
    (SELECT INVH_SYS_ID, INVH_STATUS, INVH_SM_CODE, SM_NAME FROM OT_INVOICE_HEAD, OM_SALESMAN WHERE INVH_SM_CODE = SM_CODE) R,
    (SELECT CSRH_SYS_ID, CSRH_STATUS, CSRH_SM_CODE, SM_NAME FROM OT_CUST_SALE_RET_HEAD, OM_SALESMAN WHERE CSRH_SM_CODE = SM_CODE) S,
    (SELECT AD_ANLY_TYPE, AD_ANLY_NO, AD_CODE, AD_PARENT_CODE, AD_NAME FROM OM_ANALYSIS_DETAIL) T,
    (SELECT LOCN_CODE, LOCN_NAME, LOCN_GROUP_CODE FROM OM_LOCATION) Z
    WHERE SD_COMP_CODE = :comp_code
    AND SD_SALE_LOCN_CODE IN (SELECT LUSR_LOCN_CODE FROM OM_LOCATION_USER WHERE LUSR_USER_ID = :user_id)
    AND SD_ITEM_CODE = ITEM_CODE
    AND ITEM_CODE = IU_ITEM_CODE
    AND ITEM_UOM_CODE = IU_UOM_CODE
    AND SD_SALE_LOCN_CODE = Z.LOCN_CODE
    AND SD_CUST_CODE = CUST_CODE
    AND ITEM_IG_CODE = A.VSSV_CODE(+)
    AND 'ITEM_GROUP' = A.VSSV_VS_CODE(+)
    AND 'ITEM' = C.AD_ANLY_TYPE(+) AND 1 = C.AD_ANLY_NO(+) AND ITEM_ANLY_CODE_01 = C.AD_CODE(+)
    AND 'ITEM' = D.AD_ANLY_TYPE(+) AND 2 = D.AD_ANLY_NO(+) AND ITEM_ANLY_CODE_02 = D.AD_CODE(+)
    AND 'ITEM' = E.AD_ANLY_TYPE(+) AND 3 = E.AD_ANLY_NO(+) AND ITEM_ANLY_CODE_03 = E.AD_CODE(+)
    AND 'ITEM' = F.AD_ANLY_TYPE(+) AND 4 = F.AD_ANLY_NO(+) AND ITEM_ANLY_CODE_04 = F.AD_CODE(+)
    AND 'ITEM' = G.AD_ANLY_TYPE(+) AND 5 = G.AD_ANLY_NO(+) AND ITEM_ANLY_CODE_05 = G.AD_CODE(+)
    AND 'ITEM' = H.AD_ANLY_TYPE(+) AND 6 = H.AD_ANLY_NO(+) AND ITEM_ANLY_CODE_06 = H.AD_CODE(+)
    AND 'ITEM' = I.AD_ANLY_TYPE(+) AND 7 = I.AD_ANLY_NO(+) AND ITEM_ANLY_CODE_07 = I.AD_CODE(+)
    AND 'ITEM' = J.AD_ANLY_TYPE(+) AND 8 = J.AD_ANLY_NO(+) AND ITEM_ANLY_CODE_08 = J.AD_CODE(+)
    AND 'ITEM' = K.AD_ANLY_TYPE(+) AND 9 = K.AD_ANLY_NO(+) AND ITEM_ANLY_CODE_09 = K.AD_CODE(+)
    AND 'ITEM' = L.AD_ANLY_TYPE(+) AND 10 = L.AD_ANLY_NO(+) AND ITEM_ANLY_CODE_10 = L.AD_CODE(+)
    AND 'ITEM' = M.AD_ANLY_TYPE(+) AND 11 = M.AD_ANLY_NO(+) AND ITEM_ANLY_CODE_11 = M.AD_CODE(+)
    AND 'ITEM' = N.AD_ANLY_TYPE(+) AND 13 = N.AD_ANLY_NO(+) AND ITEM_ANLY_CODE_13 = N.AD_CODE(+)
    AND 'ITEM' = O.AD_ANLY_TYPE(+) AND 15 = O.AD_ANLY_NO(+) AND ITEM_ANLY_CODE_15 = O.AD_CODE(+)
    AND 'ITEM' = P.AD_ANLY_TYPE(+) AND 19 = P.AD_ANLY_NO(+) AND ITEM_ANLY_CODE_19 = P.AD_CODE(+)
    AND 'ITEM' = Q.AD_ANLY_TYPE(+) AND 20 = Q.AD_ANLY_NO(+) AND ITEM_ANLY_CODE_20 = Q.AD_CODE(+)
    AND SD_H_SYS_ID = R.INVH_SYS_ID(+)
    AND SD_H_SYS_ID = S.CSRH_SYS_ID(+)
    AND 'CUSTOMER' = T.AD_ANLY_TYPE(+) AND 4 = T.AD_ANLY_NO(+) AND CUST_ANLY_CODE_04 = T.AD_CODE(+)
    -- Dynamic WHERE conditions will be added by ReportManager
    AND (:from_sdm_code IS NULL OR NVL(R.INVH_SM_CODE, S.CSRH_SM_CODE) >= :from_sdm_code)
    AND (:to_sdm_code IS NULL OR :to_sdm_code = 'ZZZZZZ' OR NVL(R.INVH_SM_CODE, S.CSRH_SM_CODE) <= :to_sdm_code)
    AND (:from_cust_code IS NULL OR SD_CUST_CODE >= :from_cust_code)
    AND (:to_cust_code IS NULL OR :to_cust_code = 'ZZZZZZ' OR SD_CUST_CODE <= :to_cust_code)
    AND (:from_flash_code IS NULL OR SD_ITEM_ANLY_CODE_01 >= :from_flash_code)
    AND (:to_flash_code IS NULL OR :to_flash_code = 'ZZZZZZ' OR SD_ITEM_ANLY_CODE_01 <= :to_flash_code)
    AND (:from_item_code IS NULL OR SD_ITEM_CODE >= :from_item_code)
    AND (:to_item_code IS NULL OR :to_item_code = 'ZZZZZZ' OR SD_ITEM_CODE <= :to_item_code)
    AND (:from_locn_code IS NULL OR SD_SALE_LOCN_CODE >= :from_locn_code)
    AND (:to_locn_code IS NULL OR :to_locn_code = 'ZZZZZZ' OR SD_SALE_LOCN_CODE <= :to_locn_code)
    AND (:from_date IS NULL OR SD_DT >= TO_DATE(:from_date, 'DD/MM/YYYY'))
    AND (:to_date IS NULL OR SD_DT <= TO_DATE(:to_date, 'DD/MM/YYYY'))
    ORDER BY SD_CUST_NAME, SD_DT