-- All Transactions Pending For Approval (TTL715)
-- Generated SQL file for sql_executor.py
-- File: \\reports\\sql\\TTL715.sql
-- Generated on: 2025-08-22T08:20:19.572Z

-- Parameters:
-- :FM_DT (DATE): From Date
-- :TO_DT (DATE): To Date
-- :FM_TXN_CODE (VARCHAR2): From Transaction Code
-- :TO_TXN_CODE (VARCHAR2): To Transaction Code

-- Main Query:
SELECT DISTINCT 1 ORD, PH_SYS_ID SYS_ID, PH_DT DT, PH_TXN_CODE TXN, PH_NO NUM , PH_LOCN_CODE LOCN, PH_SUPP_CODE CODE,SUPP_NAME NAME,
DECODE(NVL(A.PI_PH_SYS_ID,0), 0, 'N', 'Y') ITEM, 'Purchase Order' TXN_TYPE, PH_CR_UID "UID"
FROM   OT_PO_HEAD, OM_SUPPLIER,
(SELECT PI_PH_SYS_ID
 FROM   OT_PO_ITEM) A
WHERE  PH_SUPP_CODE = SUPP_CODE
AND    PH_SYS_ID    = A.PI_PH_SYS_ID(+)
AND    PH_APPR_UID IS NULL 
AND    NVL(PH_CLO_STATUS, 0) = 0
AND    PH_DT   BETWEEN TO_DATE(:FM_DT,'DD/MM/YYYY') AND TO_DATE(:TO_DT,'DD/MM/YYYY')
AND    PH_TXN_CODE BETWEEN :FM_TXN_CODE AND :TO_TXN_CODE
UNION ALL
SELECT DISTINCT 2 ORD,SH_SYS_ID SYS_ID, SH_DT DT, SH_TXN_CODE TXN, SH_NO NUM , NULL LOCN, SH_SUPP_CODE CODE,SUPP_NAME NAME,
DECODE(NVL(A.SI_SH_SYS_ID,0), 0, 'N', 'Y') ITEM, 'Shipment Advice' TXN_TYPE, SH_CR_UID "UID"
FROM   OT_SHIP_HEAD, OM_SUPPLIER,
(SELECT SI_SH_SYS_ID
 FROM   OT_SHIP_ITEM) A
WHERE  SH_SUPP_CODE = SUPP_CODE
AND    SH_SYS_ID    = A.SI_SH_SYS_ID(+)
AND    SH_APPR_UID IS NULL
AND    SH_DT   BETWEEN TO_DATE(:FM_DT,'DD/MM/YYYY') AND TO_DATE(:TO_DT,'DD/MM/YYYY')
AND    SH_TXN_CODE BETWEEN :FM_TXN_CODE AND :TO_TXN_CODE
UNION ALL
SELECT DISTINCT 3 ORD,IH_SYS_ID SYS_ID, IH_DT DT, IH_TXN_CODE TXN, IH_NO NUM , IH_LOCN_CODE LOCN, IH_SUPP_CODE CODE,SUPP_NAME NAME,
DECODE(NVL(A.II_IH_SYS_ID,0), 0, 'N', 'Y') ITEM, 'Packing List' TXN_TYPE,  IH_CR_UID "UID"
FROM   OT_INSP_HEAD, OM_SUPPLIER,
(SELECT II_IH_SYS_ID
 FROM   OT_INSP_ITEM) A
WHERE  IH_SUPP_CODE = SUPP_CODE
AND    IH_SYS_ID    = A.II_IH_SYS_ID(+)
AND    IH_APPR_UID IS NULL
AND    IH_DT   BETWEEN TO_DATE(:FM_DT,'DD/MM/YYYY') AND TO_DATE(:TO_DT,'DD/MM/YYYY')
AND    IH_TXN_CODE BETWEEN :FM_TXN_CODE AND :TO_TXN_CODE
UNION ALL
SELECT DISTINCT 4 ORD,GH_SYS_ID SYS_ID, GH_DT DT, GH_TXN_CODE TXN, GH_NO NUM , GH_LOCN_CODE LOCN, GH_SUPP_CODE CODE,SUPP_NAME NAME,
DECODE(NVL(A.GI_GH_SYS_ID,0), 0, 'N', 'Y') ITEM, 'Goods Receipt Note/LTI' TXN_TYPE, GH_CR_UID "UID"
FROM   OT_GR_HEAD, OM_SUPPLIER,
(SELECT GI_GH_SYS_ID
 FROM   OT_GR_ITEM) A
WHERE  GH_SUPP_CODE = SUPP_CODE(+)
AND    GH_SYS_ID    = A.GI_GH_SYS_ID(+)
AND    GH_APPR_UID IS NULL
AND    GH_DT   BETWEEN TO_DATE(:FM_DT,'DD/MM/YYYY') AND TO_DATE(:TO_DT,'DD/MM/YYYY')
AND    GH_TXN_CODE BETWEEN :FM_TXN_CODE AND :TO_TXN_CODE
UNION ALL
SELECT DISTINCT 5 ORD,SRH_SYS_ID SYS_ID, SRH_DT DT, SRH_TXN_CODE TXN, SRH_NO NUM , SRH_LOCN_CODE LOCN, SRH_SUPP_CODE CODE,SUPP_NAME NAME,
DECODE(NVL(A.SRI_SRH_SYS_ID,0), 0, 'N', 'Y') ITEM, 'Supplier Return/LTO' TXN_TYPE, SRH_CR_UID "UID"
FROM   OT_SUP_RET_HEAD, OM_SUPPLIER,
(SELECT SRI_SRH_SYS_ID
 FROM   OT_SUP_RET_ITEM) A
WHERE  SRH_SUPP_CODE = SUPP_CODE
AND    SRH_SYS_ID    = A.SRI_SRH_SYS_ID(+)
AND    SRH_APPR_UID IS NULL
AND    SRH_DT   BETWEEN TO_DATE(:FM_DT,'DD/MM/YYYY') AND TO_DATE(:TO_DT,'DD/MM/YYYY')
AND    SRH_TXN_CODE BETWEEN :FM_TXN_CODE AND :TO_TXN_CODE
UNION ALL
SELECT DISTINCT 6 ORD,MIH_SYS_ID SYS_ID, MIH_DT DT, MIH_TXN_CODE TXN, MIH_NO NUM , MIH_LOCN_CODE LOCN, NULL CODE,NULL NAME,
DECODE(NVL(A.MII_MIH_SYS_ID,0), 0, 'N', 'Y') ITEM, 'Material Issue' TXN_TYPE, MIH_CR_UID "UID"
FROM   OT_MAT_ISS_HEAD,
(SELECT MII_MIH_SYS_ID
 FROM   OT_MAT_ISS_ITEM) A
WHERE  MIH_SYS_ID    = A.MII_MIH_SYS_ID(+)
AND    MIH_APPR_UID IS NULL
AND    MIH_DT   BETWEEN TO_DATE(:FM_DT,'DD/MM/YYYY') AND TO_DATE(:TO_DT,'DD/MM/YYYY')
AND    MIH_TXN_CODE BETWEEN :FM_TXN_CODE AND :TO_TXN_CODE
UNION ALL
SELECT DISTINCT 7 ORD,MRH_SYS_ID SYS_ID, MRH_DT DT, MRH_TXN_CODE TXN, MRH_NO NUM , MRH_LOCN_CODE LOCN, NULL CODE,NULL NAME,
DECODE(NVL(A.MRI_MRH_SYS_ID,0), 0, 'N', 'Y') ITEM, 'Material Return' TXN_TYPE, MRH_CR_UID "UID"
FROM   OT_MAT_RET_HEAD,
(SELECT MRI_MRH_SYS_ID
 FROM   OT_MAT_RET_ITEM) A
WHERE  MRH_SYS_ID    = A.MRI_MRH_SYS_ID(+)
AND    MRH_APPR_UID IS NULL
AND    MRH_DT   BETWEEN TO_DATE(:FM_DT,'DD/MM/YYYY') AND TO_DATE(:TO_DT,'DD/MM/YYYY')
AND    MRH_TXN_CODE BETWEEN :FM_TXN_CODE AND :TO_TXN_CODE
UNION ALL
SELECT DISTINCT 8 ORD, ADJH_SYS_ID SYS_ID, ADJH_DT DT, ADJH_TXN_CODE TXN, ADJH_NO NUM , ADJH_LOCN_CODE LOCN, NULL CODE,NULL NAME,
DECODE(NVL(A.ADJI_ADJH_SYS_ID,0), 0, 'N', 'Y') ITEM, 'Adjustments' TXN_TYPE, ADJH_CR_UID "UID"
FROM   OT_ADJ_HEAD,
(SELECT ADJI_ADJH_SYS_ID
 FROM   OT_ADJ_ITEM) A
WHERE  ADJH_SYS_ID    = A.ADJI_ADJH_SYS_ID(+)
AND    ADJH_APPR_UID IS NULL
AND    ADJH_DT   BETWEEN TO_DATE(:FM_DT,'DD/MM/YYYY') AND TO_DATE(:TO_DT,'DD/MM/YYYY')
AND    ADJH_TXN_CODE BETWEEN :FM_TXN_CODE AND :TO_TXN_CODE
UNION ALL
SELECT DISTINCT 9 ORD, CQH_SYS_ID SYS_ID, CQH_DT DT, CQH_TXN_CODE TXN, CQH_NO NUM , CQH_LOCN_CODE LOCN, CQH_CUST_CODE CODE,CQH_CUST_NAME NAME,
DECODE(NVL(A.CQI_CQH_SYS_ID,0), 0, 'N', 'Y') ITEM, 'Customer Quotations' TXN_TYPE, CQH_CR_UID "UID"
FROM   OT_CUST_QUOT_HEAD,
(SELECT CQI_CQH_SYS_ID
 FROM   OT_CUST_QUOT_ITEM) A
WHERE  CQH_SYS_ID    = A.CQI_CQH_SYS_ID(+)
AND    CQH_APPR_UID IS NULL
AND    CQH_DT   BETWEEN TO_DATE(:FM_DT,'DD/MM/YYYY') AND TO_DATE(:TO_DT,'DD/MM/YYYY')
AND    CQH_TXN_CODE BETWEEN :FM_TXN_CODE AND :TO_TXN_CODE
UNION ALL
SELECT DISTINCT 10 ORD, SOH_SYS_ID SYS_ID, SOH_DT DT, SOH_TXN_CODE TXN, SOH_NO NUM , SOH_LOCN_CODE LOCN, SOH_CUST_CODE CODE,SOH_CUST_NAME NAME,
DECODE(NVL(A.SOI_SOH_SYS_ID,0), 0, 'N', 'Y') ITEM, 'Works Authority' TXN_TYPE, SOH_CR_UID "UID"
FROM   OT_SO_HEAD,
(SELECT SOI_SOH_SYS_ID
 FROM   OT_SO_ITEM) A
WHERE  SOH_SYS_ID    = A.SOI_SOH_SYS_ID(+)
AND    SOH_APPR_UID IS NULL
AND    NVL(SOH_CLO_STATUS, 0) = 0
AND    SOH_DT   BETWEEN TO_DATE(:FM_DT,'DD/MM/YYYY') AND TO_DATE(:TO_DT,'DD/MM/YYYY')
AND    SOH_TXN_CODE BETWEEN :FM_TXN_CODE AND :TO_TXN_CODE
UNION ALL
SELECT DISTINCT 11 ORD, INVH_SYS_ID SYS_ID, INVH_DT DT, INVH_TXN_CODE TXN, INVH_NO NUM , INVH_LOCN_CODE LOCN, INVH_CUST_CODE CODE,INVH_CUST_NAME NAME,
DECODE(NVL(A.INVI_INVH_SYS_ID,0), 0, 'N', 'Y') ITEM, 'Invoices' TXN_TYPE, INVH_CR_UID "UID"
FROM   OT_INVOICE_HEAD,
(SELECT INVI_INVH_SYS_ID
 FROM   OT_INVOICE_ITEM) A
WHERE  INVH_SYS_ID    = A.INVI_INVH_SYS_ID(+)
AND    INVH_APPR_UID IS NULL
AND    INVH_DT   BETWEEN TO_DATE(:FM_DT,'DD/MM/YYYY') AND TO_DATE(:TO_DT,'DD/MM/YYYY')
AND    INVH_TXN_CODE BETWEEN :FM_TXN_CODE AND :TO_TXN_CODE
UNION ALL
SELECT DISTINCT 12 ORD, CSRH_SYS_ID SYS_ID, CSRH_DT DT, CSRH_TXN_CODE TXN, CSRH_NO NUM , CSRH_LOCN_CODE LOCN, CSRH_CUST_CODE CODE,CSRH_CUST_NAME NAME,
DECODE(NVL(A.CSRI_CSRH_SYS_ID,0), 0, 'N', 'Y') ITEM, 'Customer Returns' TXN_TYPE, CSRH_CR_UID "UID"
FROM   OT_CUST_SALE_RET_HEAD,
(SELECT CSRI_CSRH_SYS_ID
 FROM   OT_CUST_SALE_RET_ITEM) A
WHERE  CSRH_SYS_ID    = A.CSRI_CSRH_SYS_ID(+)
AND    CSRH_APPR_UID IS NULL
AND    CSRH_DT   BETWEEN TO_DATE(:FM_DT,'DD/MM/YYYY') AND TO_DATE(:TO_DT,'DD/MM/YYYY')
AND    CSRH_TXN_CODE BETWEEN :FM_TXN_CODE AND :TO_TXN_CODE
UNION ALL
SELECT DISTINCT 13 ORD, WOH_SYS_ID SYS_ID, WOH_DT DT, WOH_TXN_CODE TXN, WOH_NO NUM , WOH_RM_LOCN_CODE LOCN, NULL CODE, NULL NAME,
DECODE(NVL(A.WOFGI_WOH_SYS_ID,0), 0, 'N', 'Y') ITEM, 'Job Open' TXN_TYPE, WOH_CR_UID "UID"
FROM   OT_WO_HEAD,
(SELECT WOFGI_WOH_SYS_ID
 FROM   OT_WO_FG_ITEM) A
WHERE  WOH_SYS_ID    = A.WOFGI_WOH_SYS_ID(+)
AND    WOH_APPR_UID IS NULL
AND    WOH_DT   BETWEEN TO_DATE(:FM_DT,'DD/MM/YYYY') AND TO_DATE(:TO_DT,'DD/MM/YYYY')
AND    WOH_TXN_CODE BETWEEN :FM_TXN_CODE AND :TO_TXN_CODE
UNION ALL
SELECT DISTINCT 14 ORD, WOAH_SYS_ID SYS_ID, WOAH_DT DT, WOAH_TXN_CODE TXN, WOAH_NO NUM , WOAH_FG_LOCN_CODE LOCN, NULL CODE, NULL NAME,
DECODE(NVL(A.WOAFGI_WOAH_SYS_ID,0), 0, 'N', 'Y') ITEM, 'Job Close' TXN_TYPE, WOAH_CR_UID "UID"
FROM   OT_WO_ACTUAL_HEAD,
(SELECT WOAFGI_WOAH_SYS_ID
 FROM   OT_WO_ACTUAL_FG_ITEM) A
WHERE  WOAH_SYS_ID    = A.WOAFGI_WOAH_SYS_ID(+)
AND    WOAH_APPR_UID IS NULL
AND    WOAH_DT   BETWEEN TO_DATE(:FM_DT,'DD/MM/YYYY') AND TO_DATE(:TO_DT,'DD/MM/YYYY')
AND    WOAH_TXN_CODE BETWEEN :FM_TXN_CODE AND :TO_TXN_CODE
UNION ALL
SELECT DISTINCT 15 ORD, LTOH_SYS_ID SYS_ID, LTOH_DT DT, LTOH_TXN_CODE TXN, LTOH_NO NUM , LTOH_FM_LOCN_CODE LOCN, NULL CODE, NULL NAME,
DECODE(NVL(A.LTOI_LTOH_SYS_ID,0), 0, 'N', 'Y') ITEM, 'Stock Transfer Out' TXN_TYPE, LTOH_CR_UID "UID"
FROM   OT_LOCN_TRF_OUT_HEAD,
(SELECT LTOI_LTOH_SYS_ID
 FROM   OT_LOCN_TRF_OUT_ITEM) A
WHERE  LTOH_SYS_ID    = A.LTOI_LTOH_SYS_ID(+)
AND    LTOH_APPR_UID IS NULL
AND    LTOH_DT   BETWEEN TO_DATE(:FM_DT,'DD/MM/YYYY') AND TO_DATE(:TO_DT,'DD/MM/YYYY')
AND    LTOH_TXN_CODE BETWEEN :FM_TXN_CODE AND :TO_TXN_CODE
UNION ALL
SELECT DISTINCT 16 ORD, LTIH_SYS_ID SYS_ID, LTIH_DT DT, LTIH_TXN_CODE TXN, LTIH_NO NUM , LTIH_FM_LOCN_CODE LOCN, NULL CODE, NULL NAME,
DECODE(NVL(A.LTII_LTIH_SYS_ID,0), 0, 'N', 'Y') ITEM, 'Stock Transfer In' TXN_TYPE, LTIH_CR_UID "UID"
FROM   OT_LOCN_TRF_IN_HEAD,
(SELECT LTII_LTIH_SYS_ID
 FROM   OT_LOCN_TRF_IN_ITEM) A
WHERE  LTIH_SYS_ID    = A.LTII_LTIH_SYS_ID(+)
AND    LTIH_APPR_UID IS NULL
AND    LTIH_DT   BETWEEN TO_DATE(:FM_DT,'DD/MM/YYYY') AND TO_DATE(:TO_DT,'DD/MM/YYYY')
AND    LTIH_TXN_CODE BETWEEN :FM_TXN_CODE AND :TO_TXN_CODE
UNION ALL
SELECT DISTINCT 17 ORD, TH_SYS_ID SYS_ID, TH_DOC_DT DT, TH_TRAN_CODE TXN, TH_DOC_NO NUM , TH_DIVN_CODE LOCN, TH_DEPT_CODE CODE,B.DEPT_NAME NAME,
DECODE(NVL(A.TD_DOC_NO,0), 0, 'N', 'Y') ITEM, 'Journals' TXN_TYPE, TH_CR_UID "UID"
FROM   FT_UNPOSTED_TRANS_HEADER,
(SELECT TD_COMP_CODE, TD_ACNT_YEAR, TD_TRAN_CODE,  TD_DOC_NO
 FROM   FT_UNPOSTED_TRANS_DETAIL) A,
(SELECT DEPT_COMP_CODE, DEPT_DIVN_CODE, DEPT_CODE, DEPT_NAME
 FROM   FM_DEPARTMENT) B
WHERE  TH_COMP_CODE    = A.TD_COMP_CODE(+)
AND    TH_ACNT_YEAR    = A.TD_ACNT_YEAR(+)
AND    TH_TRAN_CODE = A.TD_TRAN_CODE(+)
AND    TH_DOC_NO = A.TD_DOC_NO(+)
AND    TH_COMP_CODE = B.DEPT_COMP_CODE(+)
AND    TH_DIVN_CODE= B.DEPT_DIVN_CODE(+)
AND     TH_DEPT_CODE = B.DEPT_CODE(+)
AND    TH_DOC_DT   BETWEEN TO_DATE(:FM_DT,'DD/MM/YYYY') AND TO_DATE(:TO_DT,'DD/MM/YYYY')
AND    TH_TRAN_CODE BETWEEN :FM_TXN_CODE AND :TO_TXN_CODE
UNION ALL
SELECT DISTINCT 18 ORD, PDC_SEQ_NO SYS_ID, PDC_DOC_DT DT, PDC_TRAN_CODE TXN, PDC_DOC_NO NUM , PDC_DIVN_CODE LOCN, PDC_DEPT_CODE CODE,B.DEPT_NAME NAME,
 'Y' ITEM, 'Receipts' TXN_TYPE,  PDC_CR_UID "UID"
FROM   FT_PDC,
(SELECT DEPT_COMP_CODE, DEPT_DIVN_CODE, DEPT_CODE, DEPT_NAME
 FROM   FM_DEPARTMENT) B
WHERE NVL(PDC_STATUS, 'P') = 'P'
AND      PDC_COMP_CODE = B.DEPT_COMP_CODE(+)
AND    PDC_DIVN_CODE= B.DEPT_DIVN_CODE(+)
AND     PDC_DEPT_CODE = B.DEPT_CODE(+)
AND    PDC_DOC_DT   BETWEEN TO_DATE(:FM_DT,'DD/MM/YYYY') AND TO_DATE(:TO_DT,'DD/MM/YYYY')
AND    PDC_TRAN_CODE BETWEEN :FM_TXN_CODE AND :TO_TXN_CODE
ORDER BY 1, 4,2,3